### ISSUE TITLE
UI broken using Bootstrap framework

### ISSUE THREAD

**Issue by design-ev** [dpi/rng#97] opened 2016-08-18 15:57 UTC
I built out an events registration site using a theme built around the Bootstrap framework. The UI in the Messages area of this module is broken when using this CSS framework. The tokens panel does not appear, and you're unable to save new email messages.

When I switched over to the standard Bartik theme, I was able to see the available tokens and save messages just fine.

I'm not experienced enough to troubleshoot the source of this problem, but felt it was worth reporting as Bootstrap is a very popular framework.

**Comment by dpi** [comment] 2016-08-19 09:04
Thanks for the report.

The issue is caused by [Courier](https://github.com/dpi/courier). Fix will be committed in short time.

**Comment by dpi** [comment] 2016-08-19 09:09
Re-opening, let me know if you continue to have issues. Close if it works for you

**Closed as completed** 2016-08-22 19:23 UTC
Labels: defect
